### ISSUE TITLE
Can you add optional WAR packaging as well ?

### ISSUE THREAD

**Issue by javajack** [jasonish/jetty-springmvc-jsp-template#2]
Executable JAR is a very good option. But what if we also need to test the same project in a Container ? 

Is it feasible to add a WAR packaging option in this skeleton ? 

It would be a huge plus !

**Comment by jasonish** [comment]
Not really, at least not with this template..  I know some people who are using the executable war feature of the maven tomcat plugin: http://tomcat.apache.org/maven-plugin-2.0-beta-1/executable-war-jar.html

It lets you developer your app as a normal war then choose to turn it into an executable jar for deployment.

These templates are more about bolting SpringMVC onto an existing Java app that doesn't run in an container.

However, I did go down that route once before thinking it would be handy, I've learned a lot since then so may look into it again.
